---
  - hosts: all
    user: azureuser
    sudo: yes
    tasks:
    # Copy instead of linking to avoid side-effects from package updates
    - name: Set timezone to Portugal
      shell: mv /etc/localtime /etc/localtime.old
      shell: cp /usr/share/zoneinfo/Europe/Lisbon /etc/localtime
      sudo: true
